apiVersion: v2
appVersion: v1.7.8
description: File, Block, and Object Storage Services for your Cloud-Native Environment
icon: https://rook.io/images/rook-logo.svg
name: rook-ceph
sources:
  - https://github.com/rook/rook
version: v1.7.8
